services:

  # Nessie Catalog Server Using In-Memory Store
  nessie:
    image: projectnessie/nessie:latest
    container_name: catalog
    networks:
      - dremio-laptop-lakehouse
    ports:
      - 19120:19120

  # Minio Storage Server
  minio:
    image: minio/minio:latest
    container_name: storage
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      - dremio-laptop-lakehouse
    ports:
      - 9001:9001
      - 9000:9000
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - minio_data:/data

  minio-setup:
    image: minio/mc
    container_name: minio-setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (echo > /dev/tcp/minio/9000) >/dev/null 2>&1; do
        echo 'Waiting for MinIO...';
        sleep 2;
      done;
      mc alias set myminio http://minio:9000 admin password;
      mc mb myminio/datalake;
      mc ls myminio;
      "
    networks:
      - dremio-laptop-lakehouse

  # Dremio
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
      - 45678:45678
    container_name: dremio-analytics
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist -Ddebug.addDefaultUser=true
      - DREMIO_MAX_MEMORY_SIZE_MB=4096
      - DREMIO_MAX_DIRECT_MEMORY_SIZE_MB=4096
      - SERVICES_COORDINATOR_ENABLED=true
      - SERVICES_EXECUTOR_ENABLED=true
    networks:
      - dremio-laptop-lakehouse
    volumes:
      - dremio_data:/opt/dremio/data:rw
  
  dremio-setup:
    image: alpine:latest
    container_name: dremio-setup
    depends_on:
      - dremio
    volumes:
      - ./dremio-setup.sh:/dremio-setup.sh
    command: sh /dremio-setup.sh
    networks:
      - dremio-laptop-lakehouse
      
  # Superset
  superset:
    image: apache/superset
    container_name: superset
    ports:
      - "8088:8088"
    networks:
      - dremio-laptop-lakehouse
    environment:
      SUPERSET_LOAD_EXAMPLES: "yes"
      SUPERSET_SECRET_KEY: c303fcbad0ad359d6c5536dbd2614a85d3698066976ad712
      INIT_SCRIPT_PATH: /usr/src/app/.devcontainer/docker-superset-init.sh
    volumes:
      - superset_home:/app/superset_home:rw
      - .:/usr/src/app:rw
    depends_on:
      - dremio
    command: >
      /bin/bash -c "chmod +x $INIT_SCRIPT_PATH && $INIT_SCRIPT_PATH && superset run -p 8088 --with-threads --reload --debugger"
    tty: true

  # Dev environment container
  python:
    image: mcr.microsoft.com/devcontainers/python:1-3.9-bullseye
    container_name: python
    environment:
      - DBT_PROFILES_DIR=/usr/src/app/
    volumes:
      - .:/usr/src/app:rw
      - dremio_data:/mnt/dremio_data:rw
    working_dir: /usr/src/app
    command: /bin/bash -c "pip install -r dev_requirements.txt && tail -f /dev/null && /bin/bash"
    tty: true
    networks:
    - dremio-laptop-lakehouse
    depends_on:
      - dremio

networks:
  dremio-laptop-lakehouse:


volumes:
  superset_home:
  dremio_data:
  minio_data:
