services:
  # Nessie Catalog Server Using In-Memory Store
  nessie:
    image: projectnessie/nessie:latest
    container_name: catalog
    networks:
      - dremio-laptop-lakehouse
    ports:
      - 19120:19120

  # Minio Storage Server
  minio:
    image: minio/minio:latest
    container_name: storage
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=storage
      - MINIO_REGION_NAME=us-east-1
      - MINIO_REGION=us-east-1
    networks:
      - dremio-laptop-lakehouse
    ports:
      - 9001:9001
      - 9000:9000
    command: [ "server", "/data", "--console-address", ":9001" ]
    volumes:
      - minio_data:/data

  minio-setup:
    image: minio/mc
    container_name: minio-setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (echo > /dev/tcp/minio/9000) >/dev/null 2>&1; do
        echo 'Waiting for MinIO...';
        sleep 2;
      done;
      mc alias set myminio http://minio:9000 admin password;
      mc mb myminio/datalake;
      mc ls myminio;
      "
    networks:
      - dremio-laptop-lakehouse

  # Dremio
  dremio:
    image: dremio/dremio-oss:latest
    ports:
      - 9047:9047
      - 31010:31010
      - 32010:32010
      - 45678:45678
    container_name: dremio
    environment:
      - DREMIO_JAVA_SERVER_EXTRA_OPTS=-Dpaths.dist=file:///opt/dremio/data/dist -Ddebug.addDefaultUser=true
      - SERVICES_COORDINATOR_ENABLED=true
      - SERVICES_EXECUTOR_ENABLED=true
    networks:
      - dremio-laptop-lakehouse
    volumes:
      - dremio_data:/opt/dremio/data:rw
    # Workaround for permission issues in podman
    user: "0"
  
  dremio-setup:
    image: alpine:latest
    container_name: dremio-setup
    depends_on:
      - dremio
    volumes:
      - ./dremio-setup.sh:/dremio-setup.sh
    command: sh /dremio-setup.sh
    networks:
      - dremio-laptop-lakehouse
      
  # Dev environment container
  dev:
    image: mcr.microsoft.com/devcontainers/python:1-3.9-bullseye
    container_name: dev 
    environment:
      - DBT_PROFILES_DIR=/usr/src/app/
    volumes:
      - ..:/usr/src/app:rw
      - dremio_data:/mnt/dremio_data:rw
    working_dir: /usr/src/app
    command: /bin/bash -c "pip install --upgrade pip && pip install --user -r dev_requirements.txt && pip install --user . && tail -f /dev/null && /bin/bash"
    tty: true
    networks:
    - dremio-laptop-lakehouse
    depends_on:
      - dremio

networks:
  dremio-laptop-lakehouse:

volumes:
  dremio_data:
  minio_data:
