name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version for the release (e.g., 1.0.0)"
        required: true
        default: "1.0.0"

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      - name: Set up GitHub CLI
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Create Git Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@dremio.com"
          git tag -a v${{ github.event.inputs.version }} -m "Tag for release v${{ github.event.inputs.version }}"
          git push origin v${{ github.event.inputs.version }}   

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create v${{ github.event.inputs.version }} \
            --title "Release v${{ github.event.inputs.version }}" \
            --generate-notes
